/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package serialization.compare.avro;
@org.apache.avro.specific.AvroGenerated
public enum Rank implements org.apache.avro.generic.GenericEnumSymbol<Rank> {
  ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Rank\",\"namespace\":\"serialization.compare.avro\",\"symbols\":[\"ACE\",\"TWO\",\"THREE\",\"FOUR\",\"FIVE\",\"SIX\",\"SEVEN\",\"EIGHT\",\"NINE\",\"TEN\",\"JACK\",\"QUEEN\",\"KING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
