/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package serialization.compare.avro;
@org.apache.avro.specific.AvroGenerated
public enum Suit implements org.apache.avro.generic.GenericEnumSymbol<Suit> {
  SPADES, DIAMONDS, HEARTS, CLUBS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"serialization.compare.avro\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"HEARTS\",\"CLUBS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
